/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as LoginRouteImport } from './routes/login'
import { Route as App_layoutRouteImport } from './routes/app/__layout'
import { Route as AppMemoriesIndexRouteImport } from './routes/app/memories/index'
import { Route as AppMemoriesNewRouteImport } from './routes/app/memories/new'
import { Route as AppProfileIndexRouteImport } from './routes/app/profile/index'
import { Route as AppProfileEditRouteImport } from './routes/app/profile/edit'
import { Route as AppMemoriesMemoryIdIndexRouteImport } from './routes/app/memories/$memoryId/index'
import { Route as AppMemoriesMemoryIdEditRouteImport } from './routes/app/memories/$memoryId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const App_layoutRoute = App_layoutRouteImport.update({
  id: '/app/__layout',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMemoriesIndexRoute = AppMemoriesIndexRouteImport.update({
  id: '/app/memories/',
  path: '/app/memories/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMemoriesNewRoute = AppMemoriesNewRouteImport.update({
  id: '/app/memories/new',
  path: '/app/memories/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/app/profile/',
  path: '/app/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileEditRoute = AppProfileEditRouteImport.update({
  id: '/app/profile/edit',
  path: '/app/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMemoriesMemoryIdIndexRoute =
  AppMemoriesMemoryIdIndexRouteImport.update({
    id: '/app/memories/$memoryId/',
    path: '/app/memories/$memoryId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppMemoriesMemoryIdEditRoute = AppMemoriesMemoryIdEditRouteImport.update({
  id: '/app/memories/$memoryId/edit',
  path: '/app/memories/$memoryId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/app': typeof App_layoutRoute
  '/app/memories/new': typeof AppMemoriesNewRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/memories/': typeof AppMemoriesIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/memories/$memoryId/edit': typeof AppMemoriesMemoryIdEditRoute
  '/app/memories/$memoryId/': typeof AppMemoriesMemoryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/app': typeof App_layoutRoute
  '/app/memories/new': typeof AppMemoriesNewRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/memories': typeof AppMemoriesIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/memories/$memoryId/edit': typeof AppMemoriesMemoryIdEditRoute
  '/app/memories/$memoryId': typeof AppMemoriesMemoryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/app/__layout': typeof App_layoutRoute
  '/app/memories/new': typeof AppMemoriesNewRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/memories/': typeof AppMemoriesIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/memories/$memoryId/edit': typeof AppMemoriesMemoryIdEditRoute
  '/app/memories/$memoryId/': typeof AppMemoriesMemoryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/login'
    | '/app'
    | '/app/memories/new'
    | '/app/profile/edit'
    | '/app/memories/'
    | '/app/profile/'
    | '/app/memories/$memoryId/edit'
    | '/app/memories/$memoryId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/login'
    | '/app'
    | '/app/memories/new'
    | '/app/profile/edit'
    | '/app/memories'
    | '/app/profile'
    | '/app/memories/$memoryId/edit'
    | '/app/memories/$memoryId'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/login'
    | '/app/__layout'
    | '/app/memories/new'
    | '/app/profile/edit'
    | '/app/memories/'
    | '/app/profile/'
    | '/app/memories/$memoryId/edit'
    | '/app/memories/$memoryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
  App_layoutRoute: typeof App_layoutRoute
  AppMemoriesNewRoute: typeof AppMemoriesNewRoute
  AppProfileEditRoute: typeof AppProfileEditRoute
  AppMemoriesIndexRoute: typeof AppMemoriesIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppMemoriesMemoryIdEditRoute: typeof AppMemoriesMemoryIdEditRoute
  AppMemoriesMemoryIdIndexRoute: typeof AppMemoriesMemoryIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/__layout': {
      id: '/app/__layout'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof App_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/memories/': {
      id: '/app/memories/'
      path: '/app/memories'
      fullPath: '/app/memories/'
      preLoaderRoute: typeof AppMemoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/memories/new': {
      id: '/app/memories/new'
      path: '/app/memories/new'
      fullPath: '/app/memories/new'
      preLoaderRoute: typeof AppMemoriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/app/profile'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile/edit': {
      id: '/app/profile/edit'
      path: '/app/profile/edit'
      fullPath: '/app/profile/edit'
      preLoaderRoute: typeof AppProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/memories/$memoryId/': {
      id: '/app/memories/$memoryId/'
      path: '/app/memories/$memoryId'
      fullPath: '/app/memories/$memoryId/'
      preLoaderRoute: typeof AppMemoriesMemoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/memories/$memoryId/edit': {
      id: '/app/memories/$memoryId/edit'
      path: '/app/memories/$memoryId/edit'
      fullPath: '/app/memories/$memoryId/edit'
      preLoaderRoute: typeof AppMemoriesMemoryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
  App_layoutRoute: App_layoutRoute,
  AppMemoriesNewRoute: AppMemoriesNewRoute,
  AppProfileEditRoute: AppProfileEditRoute,
  AppMemoriesIndexRoute: AppMemoriesIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppMemoriesMemoryIdEditRoute: AppMemoriesMemoryIdEditRoute,
  AppMemoriesMemoryIdIndexRoute: AppMemoriesMemoryIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
